Update

diff --git a/Module_04/ex02/Makefile b/Module_04/ex02/Makefile
--- a/Module_04/ex02/Makefile
+++ b/Module_04/ex02/Makefile
@@ -10,21 +10,27 @@ SRCS = main.cpp Cat.cpp Dog.cpp Animal.cpp WrongAnimal.cpp WrongCat.cpp Brain.cp
 OBJS = ${SRCS:.cpp=.o}
 
 %.o : %.cpp Cat.hpp Dog.hpp Animal.hpp WrongCat.hpp WrongAnimal.hpp Brain.hpp
-	@${COMPILE} ${FLAGS} -c $< -o $@
-	@echo "compilation file src done 	✅"
-	@echo "create file object done 	✅"
+	@${COMPILE} ${FLAGS} -c $< -o $@ && \
+	echo "Compilation of $< done ✅" || \
+	(echo "Compilation of $< failed ❌" && exit 1)
+
+
 
 all : ${NAME}
 
 ${NAME} : ${OBJS}
-	@${COMPILE} ${OBJS} -o $@
-	@echo "create file executable done 	✅"
+	@${COMPILE} ${OBJS} -o $@ && \
+	echo "Executable ${NAME} created ✅" || \
+	(echo "Failed to create executable ${NAME} ❌" && exit 1)
 
 clean :
-	@${RM} ${OBJS}
-	@echo "Delete files objects Done 	✅"
+	@${RM} ${OBJS} && \
+	echo "Deleted object files ✅" || \
+	echo "Failed to delete object files ❌"
+
 fclean : clean
-	@${RM} ${NAME}
-	@echo "Delete file executable Done 	✅"
+	@${RM} ${NAME} && \
+	echo "Deleted executable ${NAME} ✅" || \
+	echo "Failed to delete executable ${NAME} ❌"
 
 re : fclean all
